### ISSUE TITLE
trouble installing the plugin in a docker environment

### ISSUE THREAD

**Issue by metakermit** [gnunicorn/discourse-plugin-checklist#3]
I tried to follow the [instructions from here](https://meta.discourse.org/t/install-a-plugin/19157) for installing this plugin in a Discourse running from a Docker container (based on the official instructions). The plugin is indeed located in the *plugins/* folder after following these instructions:

```
root@balkan-app:/var/www/discourse/plugins/discourse-plugin-checklist# pwd
/var/www/discourse/plugins/discourse-plugin-checklist
root@balkan-app:/var/www/discourse/plugins/discourse-plugin-checklist# ls
assets  auto_generated  docs  plugin.rb  README.md
```

But still, the `[]` and `[x]` snippets are not rendered as check-lists.

**Comment by gnunicorn** [comment]
I'm sorry @metakermit, this plugin is not supported or worked on anymore (here). Though it was working fine until a few weeks ago on a system I had managed, is ceded to work. But I will not be fixing this.

**Comment by metakermit** [comment]
OK, it seems [this fork](https://github.com/cpradio/discourse-plugin-checklist) of your project is updated to still work. I would recommend linking to it from the README to save people's time, because your project still comes up from forum posts etc.
